config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings
from django.shortcuts import redirect


urlpatterns = [
    path('', include('snsapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name="accounts"),
    path('siniagram/', include('snsapp.urls')),
    path('', include('pwa.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

snsapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import HomeView, ProfileEditView, PostCreate, AllListView, MyListView,ContentDeleteView
from django.shortcuts import redirect

app_name = 'snsapp'
urlpatterns = [
    path('', lambda request: redirect('snsapp:home', pk=1)),
    path('home/<int:pk>/', HomeView.as_view(), name='home'),
    path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'),
    path('post_content/', PostCreate.as_view(), name='post_content'),
    path('all_post/', AllListView.as_view(), name='all_post'),
    path('my_post/', MyListView.as_view(), name='my_post'),
    path('delete/<int:pk>/', ContentDeleteView.as_view(), name='delete_content'),

    # PWA対応：sw.jsを提供
    path('sw.js', TemplateView.as_view(template_name="sw.js", content_type='application/javascript'), name='sw.js'),
]

templates/account_base.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'css.html' %}
    {% block extra_css %}{% endblock %}
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    {% include 'nav.html' %}
    {% block allauth %}
      {% if messages %}
      <div>
      <strong>Messages:</strong>
      <ul>
          {% for message in messages %}
          <li>{{message}}</li>
          {% endfor %}
      </ul>
      </div>
      {% endif %}
    {% endblock %}
    {% block content %}{% endblock %}
    {% block extra_body %}{% endblock %}
    {% include 'footer.html' %}
    {% include 'js.html' %}
  </body>
</html>

templates/base.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
        <title>シニアグラム</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
        {% load bootstrap4 %}
        
        <!-- Manifestのリンク追加 -->
        <link rel="manifest" crossorigin="use-credentials" href="{% static '/manifest.json' %}">
        
        {% progressive_web_app_meta %}
    </head>
<body>
{% if not user.is_senior %}
<header class="mb-4">
   <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'snsapp:home' pk=1 %}">Siniagram</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav navbar-left">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'snsapp:post_content' %}">投稿する</a>
               </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'snsapp:home' pk=1 %}">シニアホーム</a>
            </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'snsapp:all_post' %}">みんなの投稿</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'snsapp:my_post' %}">自分の投稿</a>
               </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'snsapp:my_post' %}">アカウント</a>
                </li>

                {% endif %}
           </ul>
           <ul class="navbar-nav navbar-right">{% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-danger" href="#" data-toggle="modal" data-target="#logoutModal">{{user.nickname}}からログアウト</a>
             </li>{% else %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'account_signup' %}">新規登録</a>
               </li>{% endif %}
           </ul>
       </div>
   </nav>
</header>
{% endif %}

<!-- Logout Confirmation Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="logoutModalLabel">ログアウト確認</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        本当にログアウトしますか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <a href="{% url 'account_logout' %}" class="btn btn-danger">ログアウト</a>
      </div>
    </div>
  </div>
</div>

{% block content %}
   <!-- ここに各htmlの内容が反映される -->
{% endblock content %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS,Fontawasome -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
       integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
       crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
       integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
       crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
       integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
       crossorigin="anonymous"></script>
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>

{% block footer %}
{% endblock footer %}
</body>
</html>

templates/list_base.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-9">
            {% for item in object_list %}
            <div class="item">
                <!-- ツイートのヘッダー -->
                <div class="tweet-header d-flex align-items-center">
                    <div class="image-container" id="user-picture">
                        <img src="{% if item.created_by.avatar %}{{ item.created_by.avatar.url }}{% else %}{% static '/icon/small.png' %}{% endif %}"
                             alt="Avatar"
                             class="img-fluid rounded-circle profile-image">
                    </div>
                    <div class="ml-2 user-name">
                        <strong>{{ item.created_by.nickname }}</strong>
                        <div>
                            <p>{{ item.created_at }}</p>
                        </div>
                    </div>  
                </div>
                    <!-- ツイートの内容 -->
                    <div class="tweet-content mt-2">
                        <p>{{ item.title }}</p>
                    </div>
    
                    <!-- メイン画像の表示 -->
                    <div class="image-container" id="main-image">
                        <img src="{{ item.image.url }}" alt="Image" class="img-fluid content-image">
                    </div>
            </div>



                <!-- 削除ボタン（条件付き） -->
                {% if show_delete %}
                <button class="btn btn-danger mt-2" data-toggle="modal" data-target="#deleteModal{{ item.id }}">削除</button>

                <!-- 削除確認モーダル -->
                <div class="modal fade" id="deleteModal{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ item.id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel{{ item.id }}">削除確認</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                本当にこの投稿を削除しますか？
                            </div>
                            <div class="modal-footer">
                                <form method="post" action="{% url 'snsapp:delete_content' item.pk %}">
                                    {% csrf_token %}
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">いいえ</button>
                                    <button type="submit" class="btn btn-danger">はい</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            {% empty %}
            <p>投稿してみましょう！</p>
            {% endfor %}
        </div>
    </div>
</div>

<!-- list.css の読み込み -->
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}